# Generated by Django 4.0.5 on 2022-06-21 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_item_des'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_des',
        ),
    ]
