# Generated by Django 4.0.5 on 2022-06-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_remove_item_item_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.FileField(default='default.jpg', upload_to='static/images/items'),
        ),
    ]
